services:
  postgres:
    image: postgres:15
    container_name: library_postgres_db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: library_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: library_mailpit
    restart: always
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_api_dev
    restart: always
    ports:
      - "${PORT}:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SES_FROM_EMAIL=${SES_FROM_EMAIL}
      - REDIS_URL=redis://redis:6379
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - KINTONE_API_BASE_URL=${KINTONE_API_BASE_URL}
      - KINTONE_API_TOKEN=${KINTONE_API_TOKEN}
      - KINTONE_APP_ID=${KINTONE_APP_ID}

volumes:
  postgres_data:
  redis_data:
